//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.BrowserAgentConverter
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrowserAgentMap
    {
        public int Id { get; set; }
        public string BrowserAgentString { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public string AgentType { get; set; }
        public string AgentName { get; set; }
        public string AgentVersion { get; set; }
        public string OsType { get; set; }
        public string OsName { get; set; }
        public string OsVersionName { get; set; }
        public string OsVersionNumber { get; set; }
        public string OsProducer { get; set; }
        public string OsProducerUrl { get; set; }
        public string AgentLanguage { get; set; }
        public string AgentLanguageTag { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
