//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBSurveyVer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperimentData
    {
        public int Id { get; set; }
        public Nullable<int> ResponseId { get; set; }
        public string PreviousService { get; set; }
        public string StructureOfSite { get; set; }
        public string FilmSelectionSite { get; set; }
        public string InspiringSite { get; set; }
        public string OverallEvaluationSite { get; set; }
        public string OpenAnswerSite { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<int> ChildrenCount { get; set; }
        public string AgeChild1 { get; set; }
        public string AgeChild2 { get; set; }
        public string AgeChild3 { get; set; }
        public string AgeChild4 { get; set; }
        public string Email { get; set; }
        public string GiftChoice { get; set; }
        public Nullable<int> DontContact { get; set; }
        public string Package { get; set; }
        public string PaymentType { get; set; }
        public string AdoptService { get; set; }
        public string FilmCountPerMonth { get; set; }
        public string HowSeeFilm { get; set; }
        public string FilmType { get; set; }
        public string FilmInspiration { get; set; }
        public string PaymentTypeOther { get; set; }
        public string HowIsWebsite { get; set; }
        public string FilmFinding { get; set; }
        public string IsGoodService { get; set; }
        public string WebsiteExperienceText { get; set; }
        public string ConsiderBB { get; set; }
        public string PreferBB { get; set; }
        public string ChancesNext3Months { get; set; }
        public string ChancesNextTime { get; set; }
        public string EmailContact { get; set; }
        public string ExperimentType { get; set; }
        public Nullable<int> GroupType { get; set; }
        public Nullable<int> ExperimentFinished { get; set; }
        public string UseFilmTvSerial { get; set; }
    
        public virtual ResponseItem ResponseItem { get; set; }
    }
}
