//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBSurveyVer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperimentDefData
    {
        public int Id { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string PageName { get; set; }
        public Nullable<int> NumberOfFriends { get; set; }
        public string LabelForFriends { get; set; }
        public string ExperimentType { get; set; }
    }
}
