//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBSurveyVer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacebookFriend
    {
        public FacebookFriend()
        {
            this.FriendsPreChosen = new HashSet<FriendsPreChosen>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FBID { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string Age { get; set; }
        public string Location { get; set; }
    
        public virtual FacebookUserData FacebookUserData { get; set; }
        public virtual ICollection<FriendsPreChosen> FriendsPreChosen { get; set; }
    }
}
