//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBSurveyVer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendsPreChosen
    {
        public int Id { get; set; }
        public Nullable<int> ResponseId { get; set; }
        public Nullable<int> FriendId { get; set; }
    
        public virtual FacebookFriend FacebookFriend { get; set; }
        public virtual ResponseItem ResponseItem { get; set; }
    }
}
