//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBSurveyVer2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SocialInfluenceEntities : DbContext
    {
        public SocialInfluenceEntities()
            : base("name=SocialInfluenceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ExperimentData> ExperimentData { get; set; }
        public DbSet<ExperimentDefData> ExperimentDefData { get; set; }
        public DbSet<ExperimentFriendsShown> ExperimentFriendsShown { get; set; }
        public DbSet<ExperimentPageVisitLog> ExperimentPageVisitLog { get; set; }
        public DbSet<ExperimentServiceInfo> ExperimentServiceInfo { get; set; }
        public DbSet<FacebookFriend> FacebookFriend { get; set; }
        public DbSet<FacebookUserData> FacebookUserData { get; set; }
        public DbSet<ResponseItem> ResponseItem { get; set; }
        public DbSet<FriendsPreChosen> FriendsPreChosen { get; set; }
    }
}
