//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBSurvey
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperimentData
    {
        public int Id { get; set; }
        public Nullable<int> ResponseId { get; set; }
        public string PreviousService { get; set; }
        public string StructureOfSite { get; set; }
        public string FilmSelectionSite { get; set; }
        public string InspiringSite { get; set; }
        public string OverallEvaluationSite { get; set; }
        public string OpenAnswerSite { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<int> ChildrenCount { get; set; }
        public string AgeChild1 { get; set; }
        public string AgeChild2 { get; set; }
        public string AgeChild3 { get; set; }
        public string AgeChild4 { get; set; }
        public string Email { get; set; }
        public string GiftChoice { get; set; }
        public Nullable<int> DontContact { get; set; }
        public string Package { get; set; }
        public string PaymentType { get; set; }
        public string AdoptService { get; set; }
    
        public virtual ResponseItem ResponseItem { get; set; }
    }
}
