//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBSurvey
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponseItem
    {
        public ResponseItem()
        {
            this.ExperimentData = new HashSet<ExperimentData>();
            this.ExperimentFriendsShown = new HashSet<ExperimentFriendsShown>();
            this.FacebookUserData = new HashSet<FacebookUserData>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ExperimentId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public string IPAddress { get; set; }
    
        public virtual ICollection<ExperimentData> ExperimentData { get; set; }
        public virtual ICollection<ExperimentFriendsShown> ExperimentFriendsShown { get; set; }
        public virtual ICollection<FacebookUserData> FacebookUserData { get; set; }
        public virtual ResponseItem ResponseItem1 { get; set; }
        public virtual ResponseItem ResponseItem2 { get; set; }
    }
}
